---
title: "Movie Revenue"
output: pdf_document
---

Packages used for analysis
```{r, message = FALSE}
library(tidyverse)
library(caret)
library(Amelia)
library(stringr)
library(DataExplorer)
library(fastDummies)
library(forcats)
library(purrr)
library(lubridate)
```

# Read in the data

```{r, warning=FALSE}
movie_train <- read.csv("train.csv", stringsAsFactors = FALSE, na.strings = c("", NA))
movie_test <- read.csv("test.csv", stringsAsFactors = FALSE, na.strings = c("", NA))
movie_data <- bind_rows(movie_train, movie_test)

colnames(movie_data)[1] <- "id"
colnames(movie_train)[1] <- "id"
colnames(movie_test)[1] <- "id"
```

## Initial Plots

```{r}
# Plots of numeric variables
ggplot(movie_data, aes(x = popularity, y = revenue)) + geom_point() + geom_smooth(method = "loess", se = FALSE) + xlim(0, 300)
ggplot(movie_data, aes(x = runtime, y = revenue)) + geom_point() + geom_smooth(method = "loess", se = FALSE)
ggplot(movie_data, aes(x = budget, y = revenue)) + geom_point() + geom_smooth(method = "loess", se = FALSE)

# Plot of how many values are missing
missmap(movie_data, col = c("red", "navyblue"))
plot_missing(movie_data)
```

# Data Cleaning

## Initial Variable Dropping

Dropping some variables that we don't need at all initially

```{r}
movie_data <- movie_data %>% select(-imdb_id, -original_title, -overview, -poster_path, -status)

# Insert the release data for the one missing value
movie_data[is.na(movie_data$release_date),]$release_date <- "05/01/00"
# Change release date to a date
movie_data$release_date <- parse_date_time2(movie_data$release_date, orders = "%m%d%y", cutoff_2000 = 20L)
```

## Categorical variables

For each of these features, there is a higher average revenue when not NA than when NA

```{r}
# Analyzing features with many NAs

movie_nas <- movie_train %>%
  select(Keywords, tagline, homepage, belongs_to_collection, revenue) %>%
  mutate_at(.funs = list(cat = ~ifelse(is.na(.), 0, 1)), 
            .vars = c("Keywords", "tagline", "homepage",
                      "belongs_to_collection"))

# Keywords
mean(movie_nas[movie_nas$Keywords_cat == 1,]$revenue, na.rm = TRUE)
mean(movie_nas[movie_nas$Keywords_cat == 0,]$revenue, na.rm = TRUE)
boxplot(revenue~Keywords_cat, data = movie_nas)

# Tagline
mean(movie_nas[movie_nas$tagline_cat == 1,]$revenue)
mean(movie_nas[movie_nas$tagline_cat == 0,]$revenue)
boxplot(revenue~tagline_cat, data = movie_nas)

# Homepage
mean(movie_nas[movie_nas$homepage_cat == 1,]$revenue)
mean(movie_nas[movie_nas$homepage_cat == 0,]$revenue)
boxplot(revenue~homepage_cat, data = movie_nas)

# Collection
mean(movie_nas[movie_nas$belongs_to_collection_cat == 1,]$revenue)
mean(movie_nas[movie_nas$belongs_to_collection_cat == 0,]$revenue)
boxplot(revenue~belongs_to_collection_cat, data = movie_nas)

# Add indicator columns to main data
movie_data <- movie_data %>% 
  mutate_at(.funs = list(ind = ~ifelse(is.na(.), 0, 1)),
            .vars = c("Keywords", "tagline", "homepage",
                      "belongs_to_collection"))

# Drop columns
movie_data <- movie_data %>%
  select(-belongs_to_collection, -homepage, -tagline, -Keywords)
```

## Cast and Crew (counts for each)

```{r}
movie_data$cast_count <- str_count(movie_data$cast, "'name':\\s'")
movie_data$crew_count <- str_count(movie_data$crew, "'name':\\s'")
```

```{r}
# Most of the movies are English, so I'm going to add another indicator variable to specify if the original language was English or not
movie_data <- movie_data %>% mutate(English = ifelse(original_language == "en", 1, 0))

# Drop original langauge column
movie_data <- movie_data %>% select(-original_language)

```

### Function to extract useful data

```{r}
extract_n_most_freq_to_dummy <- function(vect, pattern, name, n_most_pattern_fun, n_most_freq=NULL) {
  
  # Get all vars into a usable list
  var_extractor <- function(x) {
      unlist(str_extract_all(x, pattern=pattern))
  }
  
  if(!is.null(n_most_freq)) {
    n_most_freq <- n_most_freq
    extracted_vars <- lapply(vect, var_extractor) %>%
      unlist()
    
    # Find n most frequently appearing vars
    var_freq <- tibble(var = extracted_vars) %>%
      group_by(var) %>%
      count() %>%
      arrange(desc(n)) %>%
      ungroup() %>%
      filter(!is.na(var)) %>%
      top_n(n_most_freq, n)
    
    # Create new regular expression for most frequently occuring vars
    var_regex <- n_most_pattern_fun(var_freq$var)
    # var_regex <- paste(var_freq$var, collapse="|") %>%
    #   str_replace_all('([^a-zA-Z0-9 |\\-])', '\\\\\\1')
    
    new_vars <- sapply(vect, function(x) {
      unlist(str_extract_all(x, var_regex))
      })
    
    dummy_vars <- qdapTools::mtabulate(new_vars) 
  }
  else {
    extracted_vars <- sapply(vect, var_extractor)
    dummy_vars <- qdapTools::mtabulate(extracted_vars)
  }
  
  colnames(dummy_vars) <- paste0(name, gsub("\\W", "", colnames(dummy_vars)))
  rownames(dummy_vars) <- 1:nrow(dummy_vars)
  
  return(dummy_vars)
}
```

## Spoken Languages

```{r}
pattern <- "(?<=')[:lower:]{2}(?=')"
pattern_fun <- function(x) {
  paste(x, collapse="|") %>%
    paste0("(?<=')(", ., ")")
}
name <- 'Sp_'
n <- 7

dummy_sp <- extract_n_most_freq_to_dummy(movie_data$spoken_languages, pattern, name, pattern_fun, n)

movie_data <- cbind(movie_data, dummy_sp)
```

```{r}
movie_data$Num_Languages <- movie_data %>%
  select(Sp_de:Sp_ru) %>%
  rowSums()
```

```{r}
# Genres
dv_g <- sapply(movie_data$genres, function(x){unlist(str_extract_all(x, '(?<=\')([A-Z])\\w+(.*?)(?=\')'))}) %>% qdapTools::mtabulate() 
colnames(dv_g) <- paste0("Genre", gsub(" ", "", colnames(dv_g)))
rownames(dv_g) <- 1:nrow(dv_g)
movie_data <- cbind(movie_data, dv_g)

# number of genres
movie_data$num_genres <- movie_data %>% select(GenreAction:GenreWestern) %>% rowSums()

# Attempt 2
# 
# pre_genre <- gregexpr(": \'(.*?)}", movie_data$genres)
# pre_genre2 <- regmatches(movie_data$genres, pre_genre)
# genres <- lapply(pre_genre2, function(x) substr(x,4,nchar(x) - 2))
# 
# movie$genre <- genres
# dv <- qdapTools::mtabulate(movie$genre); colnames(dv) <- paste0("Genre", gsub(" ", "", colnames(dv)))
# 
# movie_data <- cbind(movie_data, dv)


# Attempt 1
# 
# pre_genre <- gregexpr(": \'(.*?)}", movie_data$genres)
# pre_genre2 <- regmatches(movie_data$genres, pre_genre)
# genres <- lapply(pre_genre2, function(x) substr(x,4,nchar(x) - 2))
#
# genre_vec <- unlist(genres)
# genre_names <- names(table(genre_vec))
# genre.df <- plyr::ldply(genres, rbind)
# 
# dv <- matrix(0, ncol = length(genre_names), nrow = nrow(movie_data))
# for(i in 1:ncol(genre.df)) {
#   temp <- fastDummies::dummy_cols(genre.df[,i])
#   temp <- temp[,-1]
#   colnames(temp) <- substr(colnames(temp), 7, nchar(colnames(temp)))
#   temp[,setdiff(genre_names, colnames(temp))] <- 0
#   temp <- temp[,genre_names]
#   temp[is.na(temp)] <- 0
#   dv <- dv + temp
# }
# colnames(dv) <- gsub(" ", "",colnames(dv))
# colnames(dv) <- paste0("Genre",colnames(dv))
# movie_data <- cbind(movie_data, dv)
```



```{r country}
# Split apart all of the countries into a separate column
# >>>>>>> 738ed8b77074956705de1794c9e4fd9b8e512d5c
separated <- separate(movie_data, production_countries, sep = "\\}, \\{", into = c("Country1", "Country2", "Country3", "Country4", "Country5", "Country6", "Country7", "Country8", "Country9", "Country10", "Country11", "Country12"))

# Function to extract the country name from the json formatted text
country_name <- function(x) {
    str_extract(x, pattern = "(?<=name': ')[A-Za-z\\s]+")
}

# Apply the function to get the country name to all twelve country columns
countries <- separated %>% select(Country1:Country12) %>% map_df(~country_name(.)) %>% bind_cols(id = separated$id)

# Change any countries that have no production company to none
countries$Country1[is.na(countries$Country1)] <- "None"

# Reshape the data to long format to make country into a factor
countries_long <- countries %>% pivot_longer(Country1:Country12, names_to = "CountryNumber", values_to = "Country", values_drop_na = TRUE)

# Summarizes the number of movies for each country
Country_summary <- countries_long %>% 
  group_by(Country) %>%
  summarize(count = n()) %>% 
  arrange(desc(count))

# Changes countries to a factor. Any country that has less than 100 movies produced there is clumped in the other group
countries_fct <- countries_long %>% 
  mutate(Country = factor(Country),
         Country = fct_lump_min(Country, min = 100, other_level = "Other"))

# Make dummy variables for each country remained (and the None and Other groups)
dummy_many <- countries_fct %>% dummy_cols(select_columns = "Country")

# Combined the multiple observations into a single observation for each row
# Variables are now ready to be included in the model. 
country_dummies <- dummy_many %>% group_by(id) %>% mutate(Country_Australia = sum(Country_Australia),
                                       Country_Canada = sum(Country_Canada),
                                       Country_France = sum(Country_France),
                                       Country_Germany = sum(Country_Germany),
                                       Country_India = sum(Country_India),
                                       Country_Italy = sum(Country_Italy),
                                       Country_Japan = sum(Country_Japan),
                                       Country_Other = sum(Country_Other),
                                       Country_Russia = sum(Country_Russia),
                                       Country_Spain = sum(Country_Spain),
                                       `Country_United Kingdom` = sum(`Country_United Kingdom`),
                                       `Country_United States of America` = sum(`Country_United States of America`),
                                       Country_None = sum(Country_None)) %>% 
                                  distinct(id, .keep_all = TRUE) %>% 
                                  dplyr::select(-CountryNumber, -Country)
movie_data <- movie_data %>% bind_cols(country_dummies)
```




```{r}
# Clean production company data
pattern_fun <- function(x) {
  paste(x, collapse="|") %>%
      str_replace_all('([^a-zA-Z0-9 |\\-])', '\\\\\\1')
}

# Get all companies into a usable list
company_name <- function(x) {
    result <- unlist(str_extract_all(x, pattern = "(?<=name': ')[^']+"))
    result
}
companies <- lapply(movie_data$production_companies, company_name) %>%
  unlist()

# Find most frequently appearing companies
companies_freq <- tibble(company = companies) %>%
  group_by(company) %>%
  count() %>%
  arrange(desc(n)) %>%
  ungroup() %>%
  filter(!is.na(company)) %>%
  top_n(30, n)

# Create new regular expression for most frequent companies
company_regex <- paste(companies_freq$company, collapse="|") %>%
  str_replace_all('([^a-zA-Z0-9 |\\-])', '\\\\\\1')

new_prod_companies <- sapply(movie_data$production_companies, function(x) {
  unlist(str_extract_all(x, company_regex))
  })

dummy_companies <- qdapTools::mtabulate(new_prod_companies) 
colnames(dummy_companies) <- paste0("Comp", gsub("\\W", "", colnames(dummy_companies)))

n_obs <- nrow(dummy_companies)
rownames(dummy_companies) <- 1:n_obs

movie_data <- cbind(movie_data, dummy_companies)
```

```{r}
# Median imputation for the runtime variable
movie_data[is.na(movie_data$runtime),]$runtime <- median(movie_data[!is.na(movie_data$runtime),]$runtime)
```

```{r}
# Had dto rename these columns to get things to run
names(movie_data)[1] <- "id"
names(movie_data)[50] <- "id1"

movie_data_1 <- movie_data %>% dplyr::select(-id, -genres, -production_companies, -production_countries, -spoken_languages, -title, -cast, -crew, -id1, -crew_count)
custom_summary <- function(data, lev = NULL, model = NULL) {
out <- Metrics::rmsle(data[, "obs"], data[, "pred"])
names(out) <- c("rmsle")
out
}

movie.train <- movie_data_1[!is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
movie.test <- movie_data_1[is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
myControl <- trainControl(method = "cv",
                          number = 10,
                          summaryFunction = custom_summary)
train <- preProcess(movie.train, method = c("nzv", "zv", "pca"))
test <- preProcess(movie.test, method = c("nzv", "zv", "pca"))
movie.train <- predict(train, movie.train)
movie.test <- predict(test, movie.test)

movie.train <- movie.train %>% mutate(revenue = movie_data_1$revenue[!is.na(movie_data_1$revenue)])
movie.test <- movie.test %>% mutate(revenue = movie_data_1$revenue[is.na(movie_data_1$revenue)])
```

```{r}
tunegrid <- expand.grid(nrounds = c(40, 50, 60),
                        lambda = c(0, .01, .025),
                        alpha = c(0, .01, .025),
                        eta = c(.2, .3, .4))

xgbLinear.model <- train(log(revenue)~.,
                   data = movie.train,
                   method = "xgbLinear",
                   tuneGrid = tunegrid,
                   trControl = myControl,
                   metric = "rmsle",
                   maximize = FALSE
                  #preProcess = c("nzv", "zv", "center", "scale")
)
xgbLinear.model
```

```{r}
# Random forest
model <- train(log(revenue)~.,
                  data = movie.train,
                  method = "ranger",
                  tuneLength = 5,
                  trControl = myControl,
                  metric = "rmsle",
                  maximize = FALSE,
                  preProcess = c("nzv", "zv", "center", "scale")
)
model

preds <- predict(model, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "log-rf-preds.csv")
```

```{r}
# Glmnet
model2 <- train(log(revenue)~.,
                data = movie.train,
                method = "glmnet",
                tuneLength = 10,
                trControl = myControl,
                metric ="rmsle",
                maximize = FALSE,
                preProcess = c("nzv", "zv", "center", "scale"))
model2

preds <- predict(model2, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "glmnet-preds.csv")
```

```{r}
# Bagged MARS
model3 <- train(log(revenue)~.,
                data = movie.train,
                method = "bagEarth",
                tuneLength = 5,
                trControl = myControl,
                metric ="rmsle",
                maximize = FALSE,
                preProcess = c("nzv", "zv", "center", "scale"))
model3

preds <- predict(model3, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "mars-preds.csv")
```

```{r}
# SVM
model4 <- train(log(revenue)~.,
                data = movie.train,
                method = "svmRadial",
                tuneLength = 5,
                trControl = myControl,
                metric ="rmsle",
                maximize = FALSE,
                preProcess = c("nzv", "zv", "center", "scale"))
model4

preds <- predict(model4, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "svm-preds.csv")
```

```{r}
# tuning ranger (2.15475 score)
movie_data_1 <- movie_data %>% dplyr::select(-id, -genres, -production_companies, -production_countries, -spoken_languages, -title, -cast, -crew, -id1, -crew_count)
custom_summary <- function(data, lev = NULL, model = NULL) {
  out <- Metrics::rmsle(data[, "obs"], data[, "pred"])
  names(out) <- c("rmsle")
  out
}

movie.train <- movie_data_1[!is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
movie.test <- movie_data_1[is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
grid <- expand.grid("mtry" = c(20, 25, 30), "splitrule" = "extratrees", min.node.size = c(1, 3, 5))
movie.train <- movie.train %>% mutate(revenue = movie_data_1$revenue[!is.na(movie_data_1$revenue)])
movie.test <- movie.test %>% mutate(revenue = movie_data_1$revenue[is.na(movie_data_1$revenue)])

model.rf2 <- train(log(revenue)~.,
                  data = movie.train,
                  method = "ranger",
                  tuneGrid = grid,
                  trControl = myControl,
                  metric = "rmsle",
                  maximize = FALSE,
                  preProcess = c("nzv", "zv", "center", "scale")
)

model.rf2

preds.rf2 <- predict(model.rf2, newdata = movie.test) %>% exp()
rf.dat2 <- data.frame(id = movie_test[,1], revenue = preds.rf2)
write_csv(rf.dat2, path = "rf_nopca2.csv")

```


```{r}
# Gradient Boosting Forest (2.07568 score)

movie_data_1 <- movie_data %>% dplyr::select(-id, -genres, -production_companies, -production_countries, -spoken_languages, -title, -cast, -crew, -id1, -crew_count)
custom_summary <- function(data, lev = NULL, model = NULL) {
out <- Metrics::rmsle(data[, "obs"], data[, "pred"])
names(out) <- c("rmsle")
out
}

movie.train <- movie_data_1[!is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
movie.test <- movie_data_1[is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
myControl <- trainControl(method = "cv",
                          number = 3,
                          summaryFunction = custom_summary)

movie.train <- movie.train %>% mutate(revenue = movie_data_1$revenue[!is.na(movie_data_1$revenue)])
movie.test <- movie.test %>% mutate(revenue = movie_data_1$revenue[is.na(movie_data_1$revenue)])

grid <- expand.grid("n.trees"=500, "interaction.depth"=4, "shrinkage"=0.1, "n.minobsinnode"=20)

rfb.mod <- train(log(revenue)~.,
                 data=movie.train,
                 method="gbm",
                 tuneGrid=grid,
                 trControl=myControl,
                 metric = "rmsle",
                 verbose=F,
                 preProcess = c("nzv", "zv", "center", "scale")
                 )

preds <- predict(rfb.mod, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "rf-gboost-preds.csv")
```

```{r}
# xgbLinear (2.1869 score)

movie_data_1 <- movie_data %>% dplyr::select(-id, -genres, -production_companies, -production_countries, -spoken_languages, -title, -cast, -crew, -id1, -crew_count)
custom_summary <- function(data, lev = NULL, model = NULL) {
out <- Metrics::rmsle(data[, "obs"], data[, "pred"])
names(out) <- c("rmsle")
out
}

movie.train <- movie_data_1[!is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
movie.test <- movie_data_1[is.na(movie_data_1$revenue),] %>% dplyr::select(-revenue)
myControl <- trainControl(method = "cv",
                          number = 3,
                          summaryFunction = custom_summary)

movie.train <- movie.train %>% mutate(revenue = movie_data_1$revenue[!is.na(movie_data_1$revenue)])
movie.test <- movie.test %>% mutate(revenue = movie_data_1$revenue[is.na(movie_data_1$revenue)])

tunegrid <- expand.grid(nrounds = 60,
                        lambda = .01,
                        alpha = .01,
                        eta = .2)

xgbLinear.model <- train(log(revenue)~.,
                   data = movie.train,
                   method = "xgbLinear",
                   tuneGrid = tunegrid,
                   trControl = myControl,
                   metric = "rmsle",
                   maximize = FALSE
                  #preProcess = c("nzv", "zv", "center", "scale")
)
xgbLinear.model

preds <- predict(xgbLinear.model, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "xgbLinear-preds.csv")
```

```{r}
# xgbTree (2.09998 score) 
tunegrid <- expand.grid(eta = .25,
                        max_depth = 3,
                        colsample_bytree = .9,
                        subsample = .8,
                        nrounds = 100,
                        min_child_weight = 1,
                        gamma = .075)

xgbTree.model <- train(log(revenue)~.,
                   data = movie.train,
                   method = "xgbTree",
                   tuneGrid = tunegrid,
                   trControl = myControl,
                   metric = "rmsle",
                   maximize = FALSE
)
xgbTree.model

preds <- predict(xgbTree.model, newdata = movie.test) %>% exp()
dat <- data.frame(id = movie_test$id, revenue = preds)
write_csv(dat, "xgbTree-preds.csv")
```


```{r}
#eliminating unnecessary variables
colnames(movie_data)

#c("ï..id", "belongs_to_collection", "genres", "homepage", "imdb_id", "original_language", "original_title", "overview", "poster_path", "production_companies", "production_countries", "spoken_languages", "status", "tagline", "title", "Keywords", "cast", "crew")

#ideas
#sentiment on title
#cast and crew- make count Shane
#number of genres - McKay
```

